name: Trigger Web Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number (e.g. 1.0.10)'
        required: true
        default: '1.0.0'
      buildType:
        description: 'Build Type'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - release

jobs:
  call_web_build:
    uses: ./.github/workflows/distribute_web_builds.yml
    with:
      version: ${{ inputs.version }}
      buildType: ${{ inputs.buildType }}
    secrets: inherit